# Generated by Django 3.1.13 on 2023-03-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='doctor',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_doctor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_patient',
        ),
    ]
